[package]
name = "my_crate_72a9eb54-5002-4540-a6e6-f2620f51b550"
version = "0.1.0"
authors = ["Matias Klemola <matias.klemola@gmail.com>"]
description = "Testing Crates.io and cargo publishing functionality."
license = "MIT"

[dependencies]
